first implementation
novasamatech/nova-utils pull request #2161
Opened 2023-10-25 12:14 UTC by stepanLav

2023-11-08 07:50 UTC, pgolovkin approved these changes

2023-11-09 16:19 UTC, leohar commented on chains/v15/chains.json
> -                    "mercuryo": {},
this is mistakenly deleted I think

2023-11-09 16:20 UTC, leohar requested changes

2023-11-09 16:20 UTC, leohar commented on chains/v15/chains_dev.json
> -            },
also this

2023-11-10 09:25 UTC, stepanLav commented on chains/v15/chains.json
> -                    "mercuryo": {},
forgot to return test value, ty!

2023-11-13 08:18 UTC, leohar approved these changes

2023-11-13 08:21 UTC, merged